language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - pip install coverage
  - pip install codecov
addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
#  - coverage run --source=. -m unittest discover -s test
#  - coverage report -m
  - python -m unittest discover -s test  # when running tests manually you must use "python3" on some systems
#after_success:
#  - codecov
notifications:
  email: false
